## Numpy

In [4]:
import numpy as np
arr = np.array([1,2,3])
print(arr)
print(arr.ndim)
print(type(arr))

[1 2 3]
1
<class 'numpy.ndarray'>


# zeros array

In [8]:
import numpy as np
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# ones array

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [2]:
#Specifying your data type
import numpy as np
np.ones((3,2), dtype=np.int64)

array([[1, 1],
       [1, 1],
       [1, 1]])

# Arranging array 

In [14]:
# Arrange function
arr = np.arange(1,20,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [2]:
import numpy as np
np.ones(2, dtype=np.int64)

array([1, 1])

# Identity matrix

In [17]:
# here we use np.eye()
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Attributes 

## 1  .shape
## 2  .size
## 3  .ndim
## 4  .dtype

In [21]:
#shape
Arr = np.array([1,2,3,4,5,6])
Arr1 = np.array([[1,2,3],[4,5,6]])
print(np.shape(Arr))
print(np.shape(Arr1))

(6,)
(2, 3)


In [23]:
#size
print(np.size(Arr))
print(np.size(Arr1))

6
6


In [24]:
#.ndim
print(Arr.ndim)
print(Arr1.ndim)

1
2


In [25]:
#.dtype
print(Arr.dtype)

int64


# Fancing indexing

In [29]:
arr = np.array([10,20,30,40,50,60,70])
print(arr[[4,2,3]])
print(arr[[0,2,4]])

[50 30 40]
[10 30 50]


 # Boolean Masking

In [ ]:
arr = np.array([10,20,30,40,50,60,70])
print(arr[arr>20])
print(arr[arr>50])

# Reshape 

In [30]:
# reshape(row,column)
Arr = np.array([1,2,3,4,5,6])
print(Arr.reshape(2,3))


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# In NumPy, flattening an array means converting a multi-dimensional array into a 1D array.
"""
✅ 1. Using flatten() method
Returns a copy of the array, flattened.
✅ 2. Using ravel() method
Returns a view of the array whenever possible (more memory-efficient).
"""
import numpy as np
Arr = np.array([51,26,2,50,63,8])
flat_array = Arr.flatten()
print(flat_array," : This is copy of an array")
vi = Arr.ravel()
print(vi," : This is the opens the view of an array")

[51 26  2 50 63  8]  : This is copy of an array
[51 26  2 50 63  8]  : This is the opens the view of an array


# Inserting an element in array 

In [5]:
#np.insert(array,index,value,axis)
#The original array is not modified; np.insert() returns a new array.
"""
📌 Simple Definition of axis:
Axis 0 → Rows (think: vertical)

Axis 1 → Columns (think: horizontal)
"""
arrr=np.array([6,9,5,4,6])
print(np.insert(arrr,0,100)) # insert(array,index,number)
arrr1 = np.array([[2,1],[3,6]])
print(arrr1)
ins = np.insert(arrr1,1,[5,6],axis=1)
print(ins)

[100   6   9   5   4   6]
........ [[2 1]
 [3 6]]
[[2 5 1]
 [3 6 6]]


# Random array

In [19]:
matrix = np.random.randint(1,100,size = (5,5))
print(matrix)

[[ 2 91 85 42 49]
 [36 52 43 67 38]
 [95 51 36 62 89]
 [96 96 88 79  1]
 [49 82 91 20 51]]


In [7]:
# we can use rng function
# rng : random number generator
import numpy as np
rng = np.random.default_rng()
rng.integers(5, size=(2, 4)) 

array([[3, 0, 0, 1],
       [2, 2, 0, 3]])

# Array indexing

In [22]:
arr = np.array([1,3,5,6,9,78])
print(arr[0])
print(arr[3:5])

1
[6 9]


In [4]:
# indexing of 2d array
import numpy as np
ar = np.array([[1,2,3],[4,6,5],[5,6,9]])
print(ar[:,1])
print(ar[:,2])

[2 6 6]
[3 5 9]


# Indexing with np.where

In [23]:
#np.where(condition, value_if_true, value_if_false)
import numpy as np

arr = np.array([10, 25, 30, 45])
result = np.where(arr > 20, 'Big', 'Small')
print(result)


['Small' 'Big' 'Big' 'Big']


In [24]:
arr = np.array([10, 25, 30, 45])
index = np.where(arr > 20)
print(index)


(array([1, 2, 3]),)


# Adding, removing, and sorting elements

In [28]:
# np.sort()
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
# np.concatenate()
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6],[6,5]])
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 6, 5]])

# How to create an array from existing data

In [42]:
# This section cover np.vstack(), np.hstack()
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
print("vstack  :")
print(np.vstack((a1,a2)))
print("hstack  :")
print(np.hstack((a1,a2)))


vstack  :
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
hstack  :
[[1 1 3 3]
 [2 2 4 4]]


In [46]:
# np.hsplit()
# if you want to convert this array into 3 array
x = np.arange(1, 25).reshape(2, 12)
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [50]:
#.view(), copy()
v = x.view()
c = x.copy()
print("view")
print(v)
print("copy")
print(x)

view
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
copy
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


# Basic array operations#

In [51]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [ ]:
# Sum
a = np.array([1, 2, 3, 4])
a.sum()

In [55]:
# Using Axis
b = np.array([[1, 1], [2, 2]])
print("When axis is 0")
print(b.sum(axis=0))
print("When axis is 1")
print(b.sum(axis=1))

When axis is 0
[3 3]
When axis is 1
[2 4]


In [60]:
# Max
arr = np.array([1,3,2,6,4,5,9,8,7,6,5,4,2,4])
print(arr.max())
print(arr.min())
print(arr.sum())

9
1
66


In [63]:
#axis 
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.min(axis = 0))



[1 2 3]


In [64]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.min(axis = 1))


[1 4]


# How to get unique items and counts

In [5]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [4]:

"""
To get the indices of unique values in a NumPy array (an array of first index positions of unique values in the array),
just pass the return_index argument in np.unique() as well as your array.
"""
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


# Transposing and reshaping a matrix

In [66]:
# arr.reshape()
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [67]:
# arr.transpose(), arr.T
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

# How to reverse an array

In [69]:
# np.flip()
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [70]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [71]:
#You can easily reverse only the rows with:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [72]:
#Or reverse only the columns with:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [73]:
#You can also reverse the contents of only one column or row.
#For example, you can reverse the contents of the row at index position 1 (the second row):
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [74]:
#You can also reverse the column at index position 1 (the second column):
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


# Broadcasting

In [6]:
l = [10,20,30,40]
arr = np.array([l])
arr+10

array([[20, 30, 40, 50]])

In [7]:

ar1=np.arange(1,26).reshape(5,5)
ar1+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [8]:
ar1*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])