In [1]:
import numpy as np

In [3]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [4]:
#Get the shape of the matrix.
s.shape
data.shape 

(5, 3)

In [5]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [6]:
#Extract Math marks of all students.
math_marks = data[:,1]
print(math_marks)

[85 92 76 65 90]


In [7]:
#Find the highest Science mark.
highest_Science_mark = data[:,2]
np.max(highest_Science_mark)

np.int64(95)

In [8]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [9]:
#Increase Math marks of all students by 5.
data[:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [10]:
print(data)

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]


In [11]:
#Find how many students are younger than 19.
c=len([data[data[:,0]<19]])
c

1

In [12]:
#Calculate the average marks in each subject (column-wise mean).
math_marks = data[:,1]
Science_mark = data[:,2]
mathmean = np.mean(math_marks)
sciencemean = np.mean(Science_mark)
print(f"Avg marks in science {mathmean}")
print(f"Avg marks in maths {sciencemean}")

Avg marks in science 86.6
Avg marks in maths 83.2


In [13]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >=80) & (data[:,2] >=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [14]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])